### ISSUE TITLE
Real-time implementation

### ISSUE THREAD

**Issue by farides86** [XueYifan1995/Real-time-NMPC-for-USVs-CasADi#4]
Hi, if I may ask,

1) What do you mean by real-time requirement in your paper? Does it mean your sampling time is 0.15s and you were able to solve it below specified sampling time as shown in table 2?
2) Talking about the forthcoming work, I know its been 3 years since you published the paper, are you able to implement this code to the actual USV by generating C++ code?  I'm struggling to implement and generate C++ code of my code written in CasADi and IPOPT to the Speedgoat as target machine. It would be great to hear if you're able to do it.

Thank you very much.

**Comment by XueYifan1995** [comment]
hello, thanks for your attention.
1. Yes.
2. We have implemented MPC on USV and AUV by ACADO Toolkit (https://acado.github.io/).
The experiments of steering control are successful and the MPC code is written by c++ directly request for ACADO. We didn't use CasADi on actual robots.  But I recently learned that CasADi v3.6.5 (https://web.casadi.org/) can be written by c++ now, you can try it.






                                         
Best Regards 致以诚挚的问候， 
薛祎凡|  Yifan Xue 
哈尔滨工程大学| Harbin Engineering University
智能海洋航行器技术全国重点实验室| National Key Laboratory of Autonomous Marine Vehicle Technology















---- Replied Message ----
From  ***@***.***> Date  6/30/2024 00:25 To  ***@***.***> Cc  ***@***.***> Subject  [XueYifan1995/Real-time-NMPC-for-USVs-CasADi] Real-time implementation (Issue #4)  

Hi, if I may ask,
What do you mean by real-time requirement in your paper? Does it mean your sampling time is 0.15s and you were able to solve it below specified sampling time as shown in table 2? Talking about the forthcoming work, I know its been 3 years since you published the paper, are you able to implement this code to the actual USV by generating C++ code? I'm struggling to implement and generate C++ code of my code written in CasADi and IPOPT to the Speedgoat as target machine. It would be great to hear if you're able to do it.Thank you very much.

**Comment by farides86** [comment]
Thank you very much. Great to hear that IPOPT solver could be code generated in the CasADi v3.6.5. I quickly tried it just now, but still not working yet. Will look into it more details. Thanks again.
